name: CI/CD Workflow with ArgoCD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: "3.6.1"

    - name: Update Kubernetes resources with new image tag
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        cd kustomize
        kustomize edit set image devops-hw3=$DOCKER_USERNAME/devops-hw3:$IMAGE_TAG
        cat kustomization.yaml

    - name: Commit updated Kustomize files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "Update Kustomize files with new image tag"
        git push origin main


    - name: Sync with ArgoCD
      env:
        ARGOCD_PASSWORD: ${{ secrets.ARGOCD_PASSWORD }}
      run: |
        argocd login 72.146.57.112 --username admin --password $ARGOCD_PASSWORD
        argocd app sync devops-hw3